### ISSUE TITLE
How to resolve the following error? scan0: ERROR while getting interface flags: No such device

### ISSUE THREAD

**Issue by Prriyamvradha** [cvra/CAN-USB-dongle-fw#3]
I used the following commands in SocketCAN and I used the CANtact toolkit as a serial bus interface.ALL the commands work fine except the last command it throws the following error
scan0: ERROR while getting interface flags: No such device.
OS-Ubuntu 18.04.1

`sudo modprobe can`

`sudo modprobe can_raw`

`sudo modprobe slcan`

`slcand -o -s6 -t hw -S 3000000 /dev/ttyACM0 slcan0`

`ifconfig slcan0 up`

**Comment by antoinealb** [comment]
Hi,

I think you should address this question to the CANtact authors instead, as this is not relevant to our CAN dongle implementation.

That being said, make sure that you are running slcand as root, I think its needed.

Antoine
